### ISSUE TITLE
plugin: log method it not able to print on cln log!

### ISSUE THREAD

**Issue by vincenzopalazzo** [dart-lightning/lndart.clightning#52]

**Comment by swaptr** [comment]
Thank you for spotting this and opening an issue.
This is the error that is logged into core lightning:
`2022-06-24T00:09:21.459Z UNUSUAL plugin-cln_plugin_class_example.exe: Killing plugin: Received a JSON-RPC response for non-existent request`
My guess is that we are trying to log a message for the `id:40` and it does not allow us to do that since no request was generated for the `id:40` as stated in the `JSON-RPCv2.0` spec [here](https://www.jsonrpc.org/specification).
A workaround may be to register a `log()` method into `rpcmethods` and generate a request response every time we need to log something. 
Ps. Can't help but notice strangely this technique works with the rust plugin api [here](https://github.com/laanwj/rust-clightning-rpc/blob/master/plugin/src/plugin.rs).

**Comment by vincenzopalazzo** [comment]
Thanks to driving inside the bug of this, and maybe you are right! the log is a special request formed by the following payload:

```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "level": "",
  "message": ""
}
```

Do you want to try to make this request and see if this fixes the problem? :)

Good debugging!

P.S: It is not a response but a plain map to send to the stdio
